### ISSUE TITLE
Compatibility with Fflexible Invoice plugin.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/custom-order-numbers-woocommerce#80]
**Describe the bug**
There is an error message coming while downloading or seeing an invoice when our plugin is activated.

**To Reproduce**
1. Install this Flexible Invoice plugin - https://wordpress.org/plugins/flexible-invoices/
2. I'm attaching ajax errors as well as configuration:

1) Invoice plugin (3 attachments: documents, template and WooCommerce), rest of setting are for pro or contact address etc.

2) Custom order numbers (files with part1, 2 and 3)

[screenshots.zip](https://github.com/TycheSoftwares/custom-order-numbers-woocommerce/files/7904932/screenshots.zip)

3. Place a new order.
4. You will see the error when you will see or download the invoice.

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/37349

**Comment by nidhinikulpatel** [comment]
@ashokrane

**Comment by nidhinikulpatel** [comment]
@ashokrane  The reason for this issue:  The issue was coming from the Flexible invoice plugin and it was need the minor changes in that plugin to solve the issue.

Solution :  need to make the changes in the file BaseDecorator.php ( located at: wp-content\plugins\flexible-invoices\vendor_prefixed\wpdesk\flexible-invoices-core\src\Invoices\Decorators\ )
On line number 409, there currently the code was 
public function get_order_number() : int 
which needs to be changed to this : 
public function get_order_number() : string 
Only the word int needs to be changed to string rest all the things will remain same.

Flexible Invoice plugin author included this fix in released version.
